import = ["~/.config/alacritty/catppuccin-latte.toml"]

[font]
size = 12

# [font.normal]
# family = "UbuntuMono Nerd Font"
# family = "NotoMono"

[window.dimensions]
columns = 160
lines = 50

[window.padding]
x = 10
y = 10

[env]
TERM = "xterm-256color"
